package logic;

public class CommandType {

	public enum Command {
		ADD, DISPLAY, DELETE, CLEAR, EXIT, INVALID, SORT, SEARCH, EDIT, REDO, 
		UNDO, SORTBYSTARTTIME, SORTBYDEADLINE, MARK_As_FINISHED, MARK_AS_UNFINISHED
	}
}
